name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-only.yml@d21b0a8606441bf9ace76ad014a80a9165de3a36 # v6.2.0
    permissions:
      contents: write  # to create the GitHub Release
