name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-only.yml@3a106f414b2ee346211a9c9050a27e2f26336796 # v7.0.0
    permissions:
      contents: write  # to create the GitHub Release
