name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-only.yml@cdc42cf2f91fd796de35bdc27aaaa1057695afcc # v6.1.0
    permissions:
      contents: write  # to create the GitHub Release
