name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/validate.yml@ebf1be0e9a042e490eef4062613562225d4d206f # v5.0.0
