name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/validate.yml@7b3c075718bd3e57a5316384ef1184ab931ef847 # v3.2.0
