name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/validate.yml@3a106f414b2ee346211a9c9050a27e2f26336796 # v7.0.0
